import XCTest
@testable import AppAtticScan

/// The CycloneDX file a release ships is the only place a consumer can read
/// what went into the artifact. A pin the generator drops is a dependency that
/// no scanner sees, and the pin check that should have caught it reports a
/// green run over the shorter list, so the count is asserted against
/// Package.resolved rather than against the generator's own output.
final class DependencyInventoryTests: XCTestCase {
    private var root: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
    }

    /// One pin as SwiftPM wrote it. Decoded from the lockfile's own structure
    /// rather than scanned out of it line by line: a line scanner that stops
    /// matching the file's formatting yields a shorter list, and every pin it
    /// missed is a pin nothing here checks.
    private struct ResolvedPin: Decodable {
        /// The v1 lockfile carries the revision and version under `state`;
        /// v2 moved `version` up to the pin. Both are decoded, so the pin
        /// works whichever shape SwiftPM wrote.
        struct State: Decodable {
            let revision: String?
            let version: String?
        }
        let identity: String
        let kind: String?
        let location: String
        let version: String?
        let state: State?

        var resolvedVersion: String { version ?? state?.version ?? "" }
    }

    private struct ResolvedFile: Decodable {
        struct V2: Decodable {
            let pins: [ResolvedPin]
        }
        let pins: [ResolvedPin]?
        let v2: V2?
    }

    /// Every pin SwiftPM wrote, which is every package the build resolved,
    /// declared or transitive. The lockfile has carried both shapes across
    /// SwiftPM versions, so both are decoded and whichever has pins is the one
    /// under test.
    private func resolvedPins() throws -> [ResolvedPin] {
        let url = root.appendingPathComponent("Package.resolved")
        guard FileManager.default.fileExists(atPath: url.path) else {
            throw XCTSkip("Package.swift declares no package on this platform, so SwiftPM resolved none and wrote no lockfile")
        }
        let data = try Data(contentsOf: url)
        let decoded = try JSONDecoder().decode(ResolvedFile.self, from: data)
        let pins = decoded.pins ?? decoded.v2?.pins ?? []
        for pin in pins {
            XCTAssertFalse(pin.identity.isEmpty, "a pin in Package.resolved has no identity")
            XCTAssertFalse(pin.location.isEmpty, "\(pin.identity) has no location")
            XCTAssertFalse(pin.resolvedVersion.isEmpty, "\(pin.identity) has no version in either `version` or `state.version`")
        }
        return pins
    }

    /// The SBOM is generated by running a script, and every test below needs
    /// the same document. Generated once per process: the assertions are about
    /// the contents, and four identical subprocess runs would only make the
    /// suite slower without checking anything the first run did not.
    private static var cachedComponents: [[String: Any]]?

    private func sbomComponents(file: StaticString = #filePath, line: UInt = #line) throws -> [[String: Any]] {
        if let cached = Self.cachedComponents { return cached }
        let shell = try XCTUnwrap(whichCommand("bash"), "bash is needed to run scripts/deps.sh", file: file, line: line)
        let out = FileManager.default.temporaryDirectory
            .appendingPathComponent("appattic-sbom-\(UUID().uuidString).json")
        defer { try? FileManager.default.removeItem(at: out) }
        let (rc, stdout, stderr) = runCommand(
            [shell, root.appendingPathComponent("scripts/deps.sh").path, "sbom", out.path],
            timeout: 60
        )
        XCTAssertEqual(rc, 0, "deps.sh sbom rc=\(rc) stdout=\(stdout) stderr=\(stderr)", file: file, line: line)
        let data = try Data(contentsOf: out)
        let object = try JSONSerialization.jsonObject(with: data)
        let bom = try XCTUnwrap(object as? [String: Any], file: file, line: line)
        XCTAssertEqual(bom["bomFormat"] as? String, "CycloneDX", file: file, line: line)
        XCTAssertEqual(bom["specVersion"] as? String, "1.5", file: file, line: line)
        let components = try XCTUnwrap(bom["components"] as? [[String: Any]], file: file, line: line)
        XCTAssertFalse(components.isEmpty, "the SBOM has no components", file: file, line: line)
        Self.cachedComponents = components
        return components
    }

    /// The purl is what a consumer and a vulnerability scanner match a package
    /// by, so it has to name the source and not only the package: the identity
    /// alone is not a purl anyone can resolve, and two packages of the same
    /// name under different owners would carry the same one. The expected value
    /// is read out of the location SwiftPM pinned, so this fails if the
    /// generator stops deriving the namespace from it.
    func testSBOMNamesEverySwiftPMPinWithItsVersion() throws {
        let pins = try resolvedPins()
        XCTAssertFalse(pins.isEmpty)
        let components = try sbomComponents()
        let purls = components.compactMap { $0["purl"] as? String }

        for pin in pins {
            var namespace = pin.location
            if namespace.hasPrefix("https://") { namespace.removeFirst("https://".count) }
            if namespace.hasSuffix(".git") { namespace.removeLast(".git".count) }
            let expected = "pkg:swift/\(namespace)@\(pin.resolvedVersion)"
            let matches = purls.filter { $0 == expected }
            XCTAssertEqual(
                matches.count,
                1,
                "\(pin.identity) is pinned in Package.resolved at \(pin.location) but the SBOM lists \(matches)"
            )
        }
    }

    /// A downloaded artifact is pinned by the SHA-256 in
    /// dep-checksums.sha256 and a SwiftPM pin by the commit revision it
    /// resolved to, so the two carry digests of different lengths. Both have
    /// to be there: a component with no hash is one a consumer cannot match
    /// against the bytes it was built from.
    ///
    /// A Flatpak runtime is the one component that cannot: `flatpak
    /// build-bundle` puts the runtime in the bundle, and the manifest pins it
    /// to a branch, which is a name and not a digest. It carries
    /// appattic:pinned-by=branch instead, so the pin is on the component and a
    /// hash nobody can check is not invented for it. A component with neither a
    /// hash nor that property is the gap this asserts against: it reads like a
    /// downloaded artifact whose digest was forgotten.
    func testEveryComponentIsHashedAndCarriesAnExternalReference() throws {
        let components = try sbomComponents()
        XCTAssertFalse(components.isEmpty)
        for component in components {
            let name = component["name"] as? String ?? "?"
            let pinnedByBranch = (component["properties"] as? [[String: String]] ?? [])
                .contains { $0["name"] == "appattic:pinned-by" && $0["value"] == "branch" }
            let hashes = component["hashes"] as? [[String: String]] ?? []
            if pinnedByBranch {
                XCTAssertEqual(
                    hashes.count, 0,
                    "\(name) is pinned by branch; a hash beside that is a number nothing can check"
                )
            } else {
                XCTAssertEqual(hashes.count, 1, "\(name) has no hash in the SBOM")
                let alg = hashes.first?["alg"] ?? ""
                let content = hashes.first?["content"] ?? ""
                switch alg {
                case "SHA-256":
                    XCTAssertEqual(content.count, 64, name)
                case "SHA-1":
                    XCTAssertEqual(content.count, 40, "\(name) is not pinned to a commit revision")
                default:
                    XCTFail("\(name) records hash algorithm '\(alg)'")
                }
            }
            let refs = component["externalReferences"] as? [[String: String]] ?? []
            XCTAssertTrue(refs.first?["url"]?.hasPrefix("https://") == true, "\(name) has no https source")
        }
    }

    /// The runtime the Flatpak bundle carries is the largest third-party thing
    /// in that artifact, and the bundle ships an SBOM beside it, so a consumer
    /// reading only the inventory has to find it there. The expected value is
    /// read out of the manifest, so this fails if the generator stops carrying
    /// the runtime, and also if it names a branch the manifest does not.
    func testEveryFlatpakRuntimeIsAComponent() throws {
        let dir = root.appendingPathComponent("packaging/flatpak")
        let manifests = try FileManager.default
            .contentsOfDirectory(atPath: dir.path)
            .filter { $0.hasSuffix(".yml") }
            .sorted()
        XCTAssertFalse(manifests.isEmpty, "no Flatpak manifest to inventory a runtime from")
        let components = try sbomComponents()
        for name in manifests {
            let text = try String(contentsOf: dir.appendingPathComponent(name), encoding: .utf8)
            func value(_ key: String) -> String? {
                for line in text.split(separator: "\n") where line.hasPrefix("\(key):") {
                    return line
                        .dropFirst(key.count + 1)
                        .trimmingCharacters(in: .whitespaces)
                        .trimmingCharacters(in: CharacterSet(charactersIn: "\""))
                }
                return nil
            }
            let runtime = try XCTUnwrap(value("runtime"), "\(name) names no runtime")
            let branch = try XCTUnwrap(value("runtime-version"), "\(name) names no runtime-version")
            let matches = components.filter { $0["name"] as? String == runtime }
            XCTAssertEqual(matches.count, 1, "\(runtime) is named in \(name) but the SBOM lists \(matches.count) component(s) for it")
            XCTAssertEqual(
                matches.first?["version"] as? String, branch,
                "\(name) pins \(runtime) to \(branch), the SBOM says \(matches.first?["version"] as? String ?? "nothing")"
            )
        }
    }

    /// A purl is the key a consumer and a vulnerability scanner match a
    /// component by, so two components carrying one purl means the second is
    /// invisible to anything that looks the first up: the two architecture
    /// builds of a downloaded artifact, or two packages of the same name under
    /// different owners, differ in the qualifiers and the namespace, not in
    /// the version.
    func testSBOMPurlsAreUnique() throws {
        let components = try sbomComponents()
        var seen: [String: [String]] = [:]
        for component in components {
            let name = component["name"] as? String ?? "?"
            guard let purl = component["purl"] as? String else {
                XCTFail("\(name) has no purl in the SBOM")
                continue
            }
            seen[purl, default: []].append(name)
        }
        for (purl, names) in seen where names.count > 1 {
            XCTFail("\(names.joined(separator: ", ")) all carry the purl \(purl)")
        }
    }

    /// Every download the packaging scripts fetch has to be a component: an
    /// artifact that ships in the binary and stays out of the inventory is the
    /// gap the SBOM exists to close.
    func testEveryPinnedDownloadIsAComponent() throws {
        let sums = try String(
            contentsOf: root.appendingPathComponent("scripts/dep-checksums.sha256"),
            encoding: .utf8
        )
        let names = sums.split(separator: "\n").compactMap { line -> String? in
            let parts = line.split(whereSeparator: \.isWhitespace)
            guard parts.count == 2, parts[0].count == 64 else { return nil }
            return String(parts[1])
        }
        XCTAssertFalse(names.isEmpty)
        let components = try sbomComponents()
        for name in names {
            XCTAssertTrue(
                components.contains { ($0["name"] as? String) == name },
                "\(name) is pinned in dep-checksums.sha256 but missing from the SBOM"
            )
        }
    }

    /// The identity|SPDX-id rows scripts/deps.sh keeps for the pins, read out of
    /// that table the way `deps.sh check` reads it, so the table this asserts
    /// against is the one the gate uses rather than a second copy that could
    /// agree with itself and disagree with the script.
    private func swiftpmLicenses() throws -> [String: String] {
        let deps = try String(
            contentsOf: root.appendingPathComponent("scripts/deps.sh"),
            encoding: .utf8
        )
        let start = try XCTUnwrap(
            deps.range(of: "SWIFTPM_LICENSES=$(cat <<'EOF'\n"),
            "scripts/deps.sh has no SWIFTPM_LICENSES table"
        )
        let rest = deps[start.upperBound...]
        let end = try XCTUnwrap(
            rest.range(of: "\nEOF\n"),
            "the SWIFTPM_LICENSES table is not terminated by EOF"
        )
        var licenses: [String: String] = [:]
        for line in rest[..<end.lowerBound].split(separator: "\n") {
            let parts = line.split(separator: "|", maxSplits: 1).map(String.init)
            guard parts.count == 2 else {
                XCTFail("SWIFTPM_LICENSES row '\(line)' is not identity|SPDX-id")
                continue
            }
            let identity = parts[0].trimmingCharacters(in: .whitespaces)
            let id = parts[1].trimmingCharacters(in: .whitespaces)
            // A blank id is not an entry. deps.sh treats a row with no usable
            // id as no row at all, so storing one here would let a pin look
            // licensed to this test while the gate and the SBOM agree it is
            // not, which is the one disagreement this file exists to prevent.
            guard !id.isEmpty else {
                XCTFail("SWIFTPM_LICENSES row \(identity) has no SPDX id")
                continue
            }
            XCTAssertNil(licenses[identity], "\(identity) is listed more than once")
            licenses[identity] = id
        }
        return licenses
    }

    /// A Swift package is third-party code SwiftPM compiles into a shipped
    /// binary, so its grant ships with it and the inventory has to carry it.
    /// The field a compliance reader opens this file for is `licenses`, and a
    /// pin without one is code that is in the artifact under a grant nobody
    /// recorded.
    ///
    /// The expected ids are read out of SWIFTPM_LICENSES rather than written
    /// here again, so the assertion is that the generator emits what the table
    /// records, and the table is what the table test below keeps honest.
    func testEverySwiftPMPinCarriesItsLicence() throws {
        let pins = try resolvedPins()
        XCTAssertFalse(pins.isEmpty)
        let licenses = try swiftpmLicenses()
        let components = try sbomComponents()

        for pin in pins {
            let expected = try XCTUnwrap(
                licenses[pin.identity],
                "\(pin.identity) is pinned but has no SPDX licence in SWIFTPM_LICENSES"
            )
            let matches = components.filter { $0["name"] as? String == pin.identity }
            XCTAssertEqual(matches.count, 1, "\(pin.identity) is not exactly one SBOM component")
            let entries = matches.first?["licenses"] as? [[String: [String: String]]] ?? []
            let ids = entries.compactMap { $0["license"]?["id"] }
            XCTAssertEqual(
                ids, [expected],
                "\(pin.identity) is licensed \(expected) at its pinned revision; the SBOM says \(ids)"
            )
        }
    }

    /// Both directions of the same invariant, on the table itself: a pin with no
    /// row is code whose grant nobody wrote down, and a row with no pin is a
    /// licence on record for code no build links. `deps.sh check` fails the
    /// build on either; this fails the test suite, which is what a contributor
    /// runs before CI.
    func testSwiftPMLicenseTableMatchesTheLockfile() throws {
        let licenses = try swiftpmLicenses()
        XCTAssertFalse(licenses.isEmpty)
        let pinned = Set(try resolvedPins().map(\.identity))
        for identity in pinned {
            XCTAssertNotNil(licenses[identity], "\(identity) is pinned with no SPDX licence recorded")
        }
        for identity in licenses.keys {
            XCTAssertTrue(
                pinned.contains(identity),
                "SWIFTPM_LICENSES names \(identity), which Package.resolved does not pin"
            )
        }
    }

    /// A component that carries an empty `licenses[].license.id` looks
    /// licensed to anything scanning shape rather than content, which is worse
    /// than a component with no `licenses` key at all: the absence is visible,
    /// the blank is not. Asserting on every component rather than on one keeps
    /// the check from passing because the one package someone thought to look at
    /// happened to be filled in.
    func testNoComponentCarriesAnEmptyLicenceId() throws {
        let components = try sbomComponents()
        for component in components {
            guard let name = component["name"] as? String else { continue }
            guard let licenses = component["licenses"] as? [[String: [String: String]]] else {
                continue  // build toolchains and the Flatpak runtime carry none
            }
            let ids = licenses.compactMap { $0["license"]?["id"] }
            XCTAssertEqual(ids.count, licenses.count, "\(name) has a licence entry with no id")
            for id in ids {
                XCTAssertFalse(
                    id.trimmingCharacters(in: .whitespaces).isEmpty,
                    "\(name) is a component with an empty SPDX licence id"
                )
            }
        }
    }
}
